"""
DOTr (Department of Transportation) Procurement Monitoring Report (PMR)
CY 2021 - Combined 1st Semester (as of 05 July 2021) and 2nd Semester (as of 05 January 2022)

Data sourced from:
  - DOTr_PMR_1st_Sem_2021.pdf  (BAC for Central Office, Aviation, Railways, BRT, NCICPP, MRP-TDD, EDSA Greenways)
  - DOTr_PMR_2nd_Sem_2021.pdf  (BAC for Central Office, Aviation, Railways, BRT, NCICPP, MRP-TDD)

Each record is a dict. Key field descriptions:
  bac           – which BAC/SBAC handled the procurement
  code          – procurement code (PAP)
  project       – project/program name
  end_user      – PMO / end-user office
  mode          – mode of procurement
  source_funds  – e.g. GoP, World Bank, Loan Proceeds
  abc_php       – Approved Budget for the Contract (PHP); None if not stated
  contract_php  – actual contract price (PHP); None if not awarded / failed
  status        – "Completed", "Failed", "Cancelled", "On-Going", "Early Procurement"
  awardee       – contractor/supplier awarded; None if not applicable
  semester      – "1st" or "2nd"
  report_date   – date of the PMR snapshot

Dates are stored as ISO strings (YYYY-MM-DD) or None.
"""

import pandas as pd

# ---------------------------------------------------------------------------
# RAW RECORDS
# ---------------------------------------------------------------------------

records = [

    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-02",
        "project": "Procurement of Fuel Card Technology for the DOTr-CO",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 9_602_338.64,
        "contract_php": 7_053_634.00,
        "status": "Completed",
        "awardee": "Petron Corporation",
        "pre_proc_conference": "2020-11-26",
        "posting_ib": "2020-12-23",
        "pre_bid_conference": "2021-01-05",
        "submission_opening_bids": "2021-01-25",
        "bid_evaluation": "2021-01-27",
        "post_qualification": "2021-02-01",
        "bac_resolution": "2021-02-11",
        "notice_of_award": "2021-02-11",
        "contract_signing": "2021-04-15",
        "notice_to_proceed": "2021-04-15",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-03",
        "project": "Procurement of Lease of Photocopying Machines for the DOTr Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 3_672_900.00,
        "contract_php": 3_118_500.00,
        "status": "Completed",
        "awardee": "Otus Copy System",
        "pre_proc_conference": "2021-01-18",
        "posting_ib": "2021-01-19",
        "pre_bid_conference": "2021-01-28",
        "submission_opening_bids": "2021-02-10",
        "bid_evaluation": "2021-02-16",
        "post_qualification": "2021-02-23",
        "bac_resolution": "2021-03-09",
        "notice_of_award": "2021-03-09",
        "contract_signing": "2021-04-13",
        "notice_to_proceed": "2021-04-13",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-04",
        "project": "Procurement of Security Services for the DOTr-Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 13_888_885.20,
        "contract_php": 13_775_721.59,
        "status": "Completed",
        "awardee": "DASSIA (D'Arm Security Services Specialist & Investigation Agency) Inc.",
        "pre_proc_conference": "2021-01-28",
        "posting_ib": "2021-02-04",
        "pre_bid_conference": "2021-02-15",
        "submission_opening_bids": "2021-03-01",
        "bid_evaluation": "2021-03-08",
        "post_qualification": "2021-03-15",
        "bac_resolution": "2021-03-26",
        "notice_of_award": "2021-03-26",
        "contract_signing": "2021-04-14",
        "notice_to_proceed": "2021-04-15",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-05",
        "project": "Procurement of General Support Services for the DOTr-Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 13_292_715.10,
        "contract_php": 9_254_957.82,
        "status": "Completed",
        "awardee": "Anchor Human Resources Development Corp.",
        "pre_proc_conference": "2021-01-18",  # also 10 Feb 2021
        "posting_ib": "2021-02-15",
        "pre_bid_conference": "2021-02-23",
        "submission_opening_bids": "2021-03-08",
        "bid_evaluation": "2021-03-19",
        "post_qualification": "2021-03-26",
        "bac_resolution": "2021-04-12",
        "notice_of_award": "2021-04-12",
        "contract_signing": "2021-05-18",
        "notice_to_proceed": "2021-05-18",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-INFR-2021-01",
        "project": "Continuation of Renovation of DOTr Canteen",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 1_730_738.09,
        "contract_php": 1_527_726.22,
        "status": "Completed",
        "awardee": "Fredmark Builders and Trading",
        "pre_proc_conference": "2021-02-10",
        "posting_ib": "2021-02-15",
        "pre_bid_conference": "2021-02-23",
        "submission_opening_bids": "2021-03-08",
        "bid_evaluation": "2021-03-19",
        "post_qualification": "2021-03-25",
        "bac_resolution": "2021-04-12",
        "notice_of_award": "2021-04-12",
        "contract_signing": "2021-05-18",
        "notice_to_proceed": "2021-05-18",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-01DC",
        "project": "Procurement of Service Provider for Hauling and Disposal of Non-Hazardous Residual Wastes of DOTr Central Office and Satellite Office",
        "end_user": "GSD",
        "mode": "Direct Contracting",
        "source_funds": "GoP",
        "abc_php": 234_000.00,
        "contract_php": 234_000.00,
        "status": "Completed",
        "awardee": "Metro Clark Waste Management Corporation",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-01-15",
        "notice_of_award": "2021-01-15",
        "contract_signing": "2021-03-02",
        "notice_to_proceed": "2021-03-02",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-02N",
        "project": "Procurement of a Service Provider for the Printing of the DOTr 2020 Annual Report for Documentation",
        "end_user": "GSD",
        "mode": "Negotiated - Media Services",
        "source_funds": "GoP",
        "abc_php": 5_194_000.00,
        "contract_php": 4_500_000.00,
        "status": "Completed",
        "awardee": "Manila Bulletin",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-02-11",
        "notice_of_award": "2021-02-11",
        "contract_signing": "2021-04-06",
        "notice_to_proceed": "2021-04-07",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-03N",
        "project": "Procurement of a Service Provider for a Weekly Radio Blocktime Program of the DOTr",
        "end_user": "CCAO",
        "mode": "Negotiated - Media Services",
        "source_funds": "GoP",
        "abc_php": 9_600_000.00,
        "contract_php": 9_600_000.00,
        "status": "Completed",
        "awardee": "Manila Broadcasting Company",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-07-06",
        "notice_of_award": "2021-07-06",
        "contract_signing": "2021-07-22",
        "notice_to_proceed": "2021-07-22",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-04N",
        "project": "Procurement of Media Monitoring Services for Print, Broadcast and Online",
        "end_user": "CCAO",
        "mode": "Negotiated - Media Services",
        "source_funds": "GoP",
        "abc_php": 459_999.96,
        "contract_php": 411_000.00,
        "status": "Completed",
        "awardee": "Media Meter Inc.",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-08-17",
        "notice_of_award": "2021-08-17",
        "contract_signing": "2021-09-21",
        "notice_to_proceed": "2021-09-21",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-05DC",
        "project": "Gift Certificates for 1,553 DOTr Officials, Employees, and Personnel",
        "end_user": "DOTCEA",
        "mode": "Direct Contracting",
        "source_funds": "GoP",
        "abc_php": 12_424_000.00,
        "contract_php": 12_424_000.00,
        "status": "Completed",
        "awardee": "Sodexo Benefit Rewards Services Philippines, Inc.",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-12-10",
        "notice_of_award": "2021-12-10",
        "contract_signing": "2021-12-16",
        "notice_to_proceed": "2021-12-16",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-06DC",
        "project": "Matica Technologies EDIsecure® Products and Veikk s460 Signature Capturing Pad",
        "end_user": "Personnel Division",
        "mode": "Direct Contracting",
        "source_funds": "GoP",
        "abc_php": 235_250.00,
        "contract_php": 234_150.00,
        "status": "On-Going",
        "awardee": "Azitsorog Inc.",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-12-23",
        "notice_of_award": "2021-12-23",
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # =========================================================================
    # BAC FOR DOTr CENTRAL OFFICE — FAILURES (2nd Sem)
    # =========================================================================

    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-01",
        "project": "Security Services for the DOTr-Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 16_666_662.24,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2020-11-26",
        "posting_ib": "2020-12-03",
        "pre_bid_conference": "2020-12-11",
        "submission_opening_bids": "2021-01-06",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-06",
        "project": "Lease of Transport Service Provider for DOTr Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 36_516_005.10,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-04-27",
        "posting_ib": "2021-04-30",
        "pre_bid_conference": "2021-05-10",
        "submission_opening_bids": "2021-05-26",
        "bid_evaluation": "2021-05-31",
        "post_qualification": "2021-06-14",
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(c) - Failed bidding",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-07",
        "project": "Supply and Delivery of Various Consumable Ink Cartridges and Toner Cartridges",
        "end_user": "Supply Division",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 1_353_250.00,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-10-13",
        "posting_ib": "2021-10-20",
        "pre_bid_conference": "2021-10-28",
        "submission_opening_bids": "2021-11-09",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-07R",
        "project": "Supply and Delivery of Various Consumable Ink Cartridges and Toner Cartridges - Rebid",
        "end_user": "Supply Division",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 1_353_250.00,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-11-10",
        "posting_ib": "2021-11-11",
        "pre_bid_conference": "2021-11-19",
        "submission_opening_bids": "2021-12-01",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2021-08",
        "project": "Lease of Transport Service Provider for DOTr Central Office (2nd attempt)",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 7_042_499.10,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-10-28",
        "posting_ib": "2021-10-30",
        "pre_bid_conference": "2021-11-08",
        "submission_opening_bids": "2021-11-22",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # =========================================================================
    # BAC FOR DOTr CENTRAL OFFICE — EARLY PROCUREMENT (2nd Sem, for CY2022)
    # =========================================================================

    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2022-01DC",
        "project": "Procurement of Service Provider for Hauling and Disposal of Non-Hazardous Residual Wastes - Clark, Pampanga",
        "end_user": "GSD",
        "mode": "Direct Contracting",
        "source_funds": "GoP",
        "abc_php": 180_000.00,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-12-20",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2022-01",
        "project": "Procurement of DOTr Email Services with Hosting",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 1_780_869.50,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-12-20",
        "posting_ib": "2021-12-23",
        "pre_bid_conference": "2022-01-05",
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2022-02",
        "project": "Procurement of Security Services for the DOTr Central and Satellite Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 11_489_577.20,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-12-20",
        "posting_ib": "2021-12-24",
        "pre_bid_conference": "2022-01-05",
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2022-03",
        "project": "Procurement for the Lease of Photocopying Machines for the DOTr-Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 2_702_700.00,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-12-20",
        "posting_ib": "2021-12-24",
        "pre_bid_conference": "2022-01-05",
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2022-04",
        "project": "Lease of Transport Service Provider for DOTr Central Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 54_774_993.00,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-11-19",  # also 2021-12-20
        "posting_ib": "2021-12-24",
        "pre_bid_conference": "2022-01-05",
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-GS-2022-05",
        "project": "Procurement of General Support Services for the DOTr Central Office and Satellite Office",
        "end_user": "GSD",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 14_514_048.69,
        "contract_php": None,
        "status": "Early Procurement",
        "awardee": None,
        "pre_proc_conference": "2021-12-20",
        "posting_ib": "2021-12-24",
        "pre_bid_conference": "2022-01-05",
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # =========================================================================
    # BAC FOR DOTr CENTRAL OFFICE — 1st SEMESTER ONLY DATA
    # (items present in 1st sem but shown differently / not yet complete)
    # =========================================================================

    {
        "bac": "BAC - Central Office",
        "code": "BAC-CO-AMP-2021-03N",
        "project": "Procurement of a Service Provider for a Weekly Radio Blocktime Program of the DOTr (On-Going as of 1st Sem)",
        "end_user": "CCAO",
        "mode": "Negotiated - Media Services",
        "source_funds": "GoP",
        "abc_php": 9_600_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-07-06",
        "notice_of_award": "2021-07-06",
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },

    # =========================================================================
    # CBAC — AVIATION AND AIRPORTS SECTOR — CANCELLED (both semesters same)
    # =========================================================================

    {
        "bac": "CBAC - Aviation and Airports",
        "code": "CBAC-AIR-INFR-2021-01",
        "project": "Central Mindanao (M'lang) Airport - Rehab of PTB, Construction of Power House, VPA & Elevated Water Tank",
        "end_user": "APDU",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 32_008_995.22,
        "contract_php": None,
        "status": "Cancelled",
        "awardee": None,
        "pre_proc_conference": "2021-03-25",
        "posting_ib": "2021-06-08",
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "cancellation_resolution": "CBAC-AIR-INFR-2021-01 dated 27 June 2021",
        "semester": "2nd",
        "report_date": "2021-07-05",
    },
    {
        "bac": "CBAC - Aviation and Airports",
        "code": "CBAC-AIR-INFR-2021-02",
        "project": "Ormoc Airport - Widening of Runway and Construction of Control Tower",
        "end_user": "APDU",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 189_996_315.88,
        "contract_php": None,
        "status": "Cancelled",
        "awardee": None,
        "pre_proc_conference": "2021-03-25",
        "posting_ib": "2021-06-08",
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "cancellation_resolution": "CBAC-AIR-INFR-2021-02 dated 27 June 2021",
        "semester": "2nd",
        "report_date": "2021-07-05",
    },
    {
        "bac": "CBAC - Aviation and Airports",
        "code": "CBAC-AIR-INFR-2021-03",
        "project": "Zamboanga International Airport - Rehabilitation of PTB and Runway Strip Grade Correction",
        "end_user": "APDU",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 77_019_225.90,
        "contract_php": None,
        "status": "Cancelled",
        "awardee": None,
        "pre_proc_conference": "2021-03-25",
        "posting_ib": "2021-06-08",
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "cancellation_resolution": "CBAC-AIR-INFR-2021-03 dated 27 June 2021",
        "semester": "2nd",
        "report_date": "2021-07-05",
    },
    {
        "bac": "CBAC - Aviation and Airports",
        "code": "CBAC-AIR-INFR-2021-04",
        "project": "Antique Airport - Widening of Runway and Runway Extension",
        "end_user": "APDU",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 88_193_700.00,
        "contract_php": None,
        "status": "Cancelled",
        "awardee": None,
        "pre_proc_conference": "2021-03-25",
        "posting_ib": "2021-06-08",
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "cancellation_resolution": "CBAC-AIR-INFR-2021-04 dated 27 June 2021",
        "semester": "2nd",
        "report_date": "2021-07-05",
    },

    # =========================================================================
    # CBAC — RAILWAYS SECTOR
    # =========================================================================

    # Completed (2nd Sem)
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-AMP-2021-01N",
        "project": "Consulting Services: Procurement of Highly Technical Consultant for the National Standard (NS) based Interoperable Automatic Fare Collection (AFC)",
        "end_user": "AFCS PMO",
        "mode": "Negotiated - HTC",
        "source_funds": "GoP",
        "abc_php": 13_000_000.00,
        "contract_php": 9_590_000.00,
        "status": "Completed",
        "awardee": "Mr. Youngwook Park",
        "pre_proc_conference": "2021-03-25",  # also 18 May 2021
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-06-21",
        "notice_of_award": "2021-06-21",
        "contract_signing": "2021-08-05",
        "notice_to_proceed": "2021-08-05",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # Failures (2nd Sem)
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-GS-2021-01",
        "project": "Procurement of Printing Services",
        "end_user": "PRI",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 9_999_999.99,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-05-25",  # also 07 July 2021, 16 July 2021
        "posting_ib": "2021-07-23",
        "pre_bid_conference": "2021-08-02",
        "submission_opening_bids": "2021-08-16",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-GS-2021-01R",
        "project": "Procurement of Printing Services - Rebid",
        "end_user": "PRI",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 9_999_999.99,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-08-26",
        "posting_ib": "2021-09-01",
        "pre_bid_conference": "2021-09-09",
        "submission_opening_bids": "2021-09-23",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-GS-2021-02",
        "project": "Development and Implementation of the Philippine Railways Institute's Overall Brand",
        "end_user": "PRI",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 2_994_697.10,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-10-28",  # also 29 Nov 2021
        "posting_ib": "2021-12-02",
        "pre_bid_conference": "2021-12-10",
        "submission_opening_bids": "2021-12-22",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(a) - No bids received",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # On-Going (2nd Sem) - Negotiated after repeated failed bidding
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-GS-2021-01N",
        "project": "Procurement of Printing Services (Negotiated after Failed Bidding)",
        "end_user": "PRI",
        "mode": "Negotiated Procurement",
        "source_funds": "GoP",
        "abc_php": 9_999_999.99,
        "contract_php": 8_490_000.00,
        "status": "On-Going",
        "awardee": "VJ Graphics Art, Inc.",
        "pre_proc_conference": None,
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": "2021-12-31",
        "notice_of_award": "2021-12-31",
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # On-Going (1st Sem only)
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-AMP-2021-01N",
        "project": "Consulting Services: Procurement of Highly Technical Consultant for the National Standard (NS) based Interoperable Automatic Fare Collection (AFC)",
        "end_user": "AFCS PMO",
        "mode": "Negotiated - HTC",
        "source_funds": "GoP",
        "abc_php": 13_000_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-03-25",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },
    {
        "bac": "CBAC - Railways",
        "code": "NSCR-ASMS",
        "project": "Supply, Delivery, Installation and Configuration of a Customized Asset and Supply Management System (ASMS) with Cloud Hosting Maintenance, and Support Services",
        "end_user": "NSCR",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 6_292_880.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-05-25",  # also 07 July 2021
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },
    {
        "bac": "CBAC - Railways",
        "code": "CBAC-RAIL-GS-2021-01-1st",
        "project": "Procurement of Printing Services (1st Sem On-Going)",
        "end_user": "PRI",
        "mode": "Public Bidding",
        "source_funds": "GoP",
        "abc_php": 9_999_999.99,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-05-25",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },

    # =========================================================================
    # SBAC — BRT (Cebu Bus Rapid Transit)
    # =========================================================================

    # 2nd Sem - Failed
    {
        "bac": "SBAC - BRT",
        "code": "SBAC-BRT-CBRT-PKG1",
        "project": "Cebu Bus Rapid Transit (CBRT) Package 1: Works Capitol to Cebu South Bus Terminal (CSBT), Urban Realm Enhancement (Link to the port)",
        "end_user": "Road Sector",
        "mode": "International Competitive Bidding",
        "source_funds": "World Bank",
        "abc_php": 1_048_627_858.00,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2021-01-15",  # also 21 Jan 2021, 02 Feb 2021
        "posting_ib": "2021-02-08",
        "pre_bid_conference": "2021-03-02",
        "submission_opening_bids": "2021-04-14",
        "bid_evaluation": "2021-04-16",
        "post_qualification": "2021-06-03",
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Rejection of All Bids under the World Bank Guidelines",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    # 1st Sem - On-Going
    {
        "bac": "SBAC - BRT",
        "code": "SBAC-BRT-CBRT-PKG1-1st",
        "project": "Cebu Bus Rapid Transit (CBRT) Package 1: Works Capitol to Cebu South Bus Terminal (CSBT), Urban Realm Enhancement (1st Sem)",
        "end_user": "Road Sector",
        "mode": "International Competitive Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 1_048_627_858.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-01-15",
        "posting_ib": "2021-02-08",
        "pre_bid_conference": "2021-03-02",
        "submission_opening_bids": "2021-04-14",
        "bid_evaluation": "2021-04-16",
        "post_qualification": "2021-06-03",
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },

    # SBAC BRT Below 250M (1st Sem only)
    {
        "bac": "SBAC - BRT (Below 250M)",
        "code": "SBAC-BRT-B250-FMS",
        "project": "CBRT Financial Management Specialist",
        "end_user": "Road Sector",
        "mode": "Public Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 2_850_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-05-14",  # also 01 June 2021, 07 July 2021
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },
    {
        "bac": "SBAC - BRT (Below 250M)",
        "code": "SBAC-BRT-B250-PA",
        "project": "CBRT Procurement Advisor",
        "end_user": "Road Sector",
        "mode": "Public Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 8_550_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-02-09",  # also Mar 22, Mar 31, May 14, Jun 01, Jul 07
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "semester": "1st",
        "report_date": "2021-07-05",
    },

    # =========================================================================
    # SBAC — NCICPP (New Cebu International Container Port Project)
    # =========================================================================

    {
        "bac": "SBAC - NCICPP",
        "code": "SBAC-NCICPP-CIVWORKS",
        "project": "New Cebu International Container Port Project Component A: Civil Works",
        "end_user": "MARITIME",
        "mode": "Public Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 5_900_950_000.00,  # PHP 5,900.95 million
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2020-09-03",
        "posting_ib": "2021-01-12",
        "pre_bid_conference": None,
        "submission_opening_bids": "2021-01-20",
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "notes": "On-going pre-qualification process; PQ Evaluation Reporting: 06 April 2021; Re-evaluation: 16 June 2021; Approval by Kexim Bank: 15 July 2021",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # =========================================================================
    # SBAC — MRP-TDD (Mindanao Railway Project: Tagum-Davao-Digos)
    # =========================================================================

    # Failure (original)
    {
        "bac": "SBAC - MRP-TDD",
        "code": "SBAC-MRP-CS-2020-01",
        "project": "Procurement of the Project Management Consultant for the Mindanao Railway Project: Tagum-Davao-Digos Segment (MRP-TDD)",
        "end_user": "Mindanao Railways Project",
        "mode": "Limited Competitive Bidding",
        "source_funds": "Loan Proceeds from CIDCA",
        "abc_php": 3_094_251_412.00,
        "contract_php": None,
        "status": "Failed",
        "awardee": None,
        "pre_proc_conference": "2020-09-18",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": "2020-10-19",
        "bid_evaluation": "2020-11-05",
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "failure_reason": "Section 35.1(b)",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },
    # Rebid - On-Going (2nd Sem) / Completed
    {
        "bac": "SBAC - MRP-TDD",
        "code": "SBAC-MRP-CS-2020-01R",
        "project": "Procurement of the Project Management Consultant for the MRP-TDD - Rebid",
        "end_user": "Mindanao Railways Project",
        "mode": "Limited Competitive Bidding",
        "source_funds": "Loan Proceeds from CIDCA",
        "abc_php": 3_094_251_412.00,
        "contract_php": 3_077_730_718.00,
        "status": "On-Going",  # Award resolution issued, contract signed
        "awardee": "China Railways Design Corporation and Guangzhou Wanan Construction Supervision Co., Ltd. Consortium",
        "pre_proc_conference": "2020-12-03",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": "2020-12-17",
        "bid_evaluation": "2021-01-04",
        "post_qualification": None,
        "bac_resolution": "2021-08-03",
        "notice_of_award": "2021-08-03",
        "contract_signing": None,
        "notice_to_proceed": None,
        "notes": "Technical bid submitted 11-Feb-21; Financial bid opened 16-Mar-21; Negotiation completed 17-May-21",
        "semester": "2nd",
        "report_date": "2022-01-05",
    },

    # =========================================================================
    # SBAC — EDSA GREENWAYS (1st Sem only)
    # =========================================================================

    {
        "bac": "SBAC - EDSA Greenways",
        "code": "EDSA-GW-CP01",
        "project": "EDSA Greenways Project for Packages CP01 (Balintawak & Cubao) Design and Build of Elevated Walkways",
        "end_user": "Road Sector",
        "mode": "International Competitive Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 4_287_910_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-01-08",  # also 24 Feb, 19 Mar, 13 Apr, 26 Apr, 29 Apr 2021
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "notes": "As of March 2021",
        "semester": "1st",
        "report_date": "2021-07-05",
    },
    {
        "bac": "SBAC - EDSA Greenways",
        "code": "EDSA-GW-CP02",
        "project": "EDSA Greenways Project for Packages CP02 (Guadalupe & Taft) Design and Build of Elevated Walkways",
        "end_user": "Road Sector",
        "mode": "International Competitive Bidding",
        "source_funds": "Loan Proceeds",
        "abc_php": 2_910_890_000.00,
        "contract_php": None,
        "status": "On-Going",
        "awardee": None,
        "pre_proc_conference": "2021-01-08",
        "posting_ib": None,
        "pre_bid_conference": None,
        "submission_opening_bids": None,
        "bid_evaluation": None,
        "post_qualification": None,
        "bac_resolution": None,
        "notice_of_award": None,
        "contract_signing": None,
        "notice_to_proceed": None,
        "notes": "As of March 2021",
        "semester": "1st",
        "report_date": "2021-07-05",
    },
]


# ---------------------------------------------------------------------------
# BUILD DATAFRAMES
# ---------------------------------------------------------------------------

def build_dataframe(records: list[dict]) -> pd.DataFrame:
    """Convert raw records list to a cleaned DataFrame."""
    df = pd.DataFrame(records)

    # Coerce date columns
    date_cols = [
        "pre_proc_conference", "posting_ib", "pre_bid_conference",
        "submission_opening_bids", "bid_evaluation", "post_qualification",
        "bac_resolution", "notice_of_award", "contract_signing",
        "notice_to_proceed",
    ]
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    # Numeric
    df["abc_php"] = pd.to_numeric(df["abc_php"], errors="coerce")
    df["contract_php"] = pd.to_numeric(df["contract_php"], errors="coerce")

    # Derived columns
    df["savings_php"] = df["abc_php"] - df["contract_php"]
    df["savings_pct"] = (df["savings_php"] / df["abc_php"] * 100).round(2)

    return df


def get_central_office(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["bac"] == "BAC - Central Office"].copy()

def get_completed(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["status"] == "Completed"].copy()

def get_failed(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["status"] == "Failed"].copy()

def get_cancelled(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["status"] == "Cancelled"].copy()

def get_by_bac(df: pd.DataFrame, bac_name: str) -> pd.DataFrame:
    return df[df["bac"] == bac_name].copy()

def get_by_semester(df: pd.DataFrame, sem: str) -> pd.DataFrame:
    """sem: '1st' or '2nd'"""
    return df[df["semester"] == sem].copy()


# ---------------------------------------------------------------------------
# SUMMARY STATISTICS
# ---------------------------------------------------------------------------

def print_summary(df: pd.DataFrame):
    print("=" * 65)
    print("DOTr PMR CY 2021 — SUMMARY")
    print("=" * 65)
    print(f"Total records      : {len(df)}")
    print(f"\nRecords by status:")
    print(df["status"].value_counts().to_string())
    print(f"\nRecords by BAC:")
    print(df["bac"].value_counts().to_string())
    print(f"\nTotal ABC (all)    : PHP {df['abc_php'].sum():,.2f}")
    completed = df[df["status"] == "Completed"]
    print(f"Total ABC (completed): PHP {completed['abc_php'].sum():,.2f}")
    print(f"Total Contract (completed): PHP {completed['contract_php'].sum():,.2f}")
    print(f"Total Savings (completed): PHP {completed['savings_php'].sum():,.2f}")
    print("=" * 65)


# ---------------------------------------------------------------------------
# ENTRYPOINT
# ---------------------------------------------------------------------------

df = build_dataframe(records)
print_summary(df)

# if __name__ == "__main__":
#     df = build_dataframe(records)
#     print_summary(df)

#     # Example: show completed Central Office procurements
#     print("\n--- Completed CO Procurements ---")
#     co_done = get_completed(get_central_office(df))
#     print(co_done[["code", "project", "abc_php", "contract_php", "savings_php", "awardee"]].to_string(index=False))

#     # Example: failed biddings
#     print("\n--- Failed Biddings ---")
#     failed = get_failed(df)
#     print(failed[["bac", "code", "project", "abc_php", "failure_reason" if "failure_reason" in failed.columns else "status"]].to_string(index=False))
